/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A trading terminal instance driven by JSON commands. */
export declare class Terminal {
  /** Build a terminal from a JSON config string. */
  constructor(configJson: string)
  /** Apply a command JSON and return the resulting frame JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
