"""Assert that every place carrying the release version agrees.

The version lives in twenty-odd files across six package managers, and a bump
that misses one produces a release where, say, the npm package pins a native
binary that was never published. That failure surfaces at install time, on a
user's machine, after the tag is irreversible -- so it is worth a cheap check
before the tag rather than a patch release after it.

    python scripts/check_version_sync.py                   # all files agree
    python scripts/check_version_sync.py --previous 0.1.0  # and none is stale

The file list is explicit rather than a repository-wide grep on purpose:
`Cargo.lock` records third-party crates that will occasionally sit at the same
version as this project, and a grep that matched those would either be noisy or
be silenced with exceptions that outlive their reason. The issue templates carry
the version too, as an example a reporter overwrites, and they are not
declarations of anything.

Counts are exact, not "at least one". A pattern that should match six platform
dependencies and finds five has found the bug this file exists for.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# (path, description, pattern with @V@ standing in for the version, expected count)
TOUCHPOINTS: list[tuple[str, str, str, int]] = [
    ("Cargo.toml", "workspace version", r'(?m)^version = "@V@"$', 1),
    # The workspace pins its own core by path AND version, so a bump that misses
    # it publishes a terminal depending on a core version that does not exist.
    (
        "Cargo.toml",
        "wickra-terminal-core path dependency",
        r'wickra-terminal-core = \{ version = "@V@"',
        1,
    ),
    # The WASM binding pins the core the same way and is easy to forget: it is
    # the one binding that is not a workspace member of the same shape.
    (
        "bindings/wasm/Cargo.toml",
        "wickra-terminal-core path dependency",
        r'version = "@V@"',
        1,
    ),
    ("bindings/python/pyproject.toml", "wheel version", r'(?m)^version = "@V@"$', 1),
    ("bindings/node/package.json", "package version", r'"version": "@V@"', 1),
    (
        "bindings/node/package.json",
        "optional platform dependencies",
        r'"wickra-terminal-[a-z0-9-]+": "@V@"',
        6,
    ),
    ("bindings/r/DESCRIPTION", "R package version", r"(?m)^Version: @V@$", 1),
    ("bindings/java/pom.xml", "Maven version", r"<version>@V@</version>", 1),
    (
        "bindings/csharp/WickraTerminal/WickraTerminal.csproj",
        "NuGet version",
        r"<Version>@V@</Version>",
        1,
    ),
    # The Maven install snippet a reader copies verbatim.
    ("bindings/java/README.md", "install snippet", r"@V@", 1),
    # The supported-version row. A security policy naming a version nobody can
    # install is worse than one naming none.
    ("SECURITY.md", "supported version", r"@V@", 1),
    # Both consume their sibling through a `file:` reference rather than a
    # version pin, so only their own version is ours to keep in step.
    ("examples/node/package.json", "example version", r'"version": "@V@"', 1),
    ("web/package.json", "web renderer version", r'"version": "@V@"', 1),
]

# Each platform package declares its own version.
PLATFORMS = [
    "darwin-arm64",
    "darwin-x64",
    "linux-arm64-gnu",
    "linux-x64-gnu",
    "win32-arm64-msvc",
    "win32-x64-msvc",
]
for platform in PLATFORMS:
    TOUCHPOINTS.append(
        (
            f"bindings/node/npm/{platform}/package.json",
            "platform package version",
            r'"version": "@V@"',
            1,
        )
    )

# Generated files: regenerated by their own toolchain, checked here so a bump
# that forgot to rebuild them is caught before the tag rather than at install.
# Only presence is asserted, not a count -- the count is the generator's business
# and changes when the generator does, which would make an exact number a false
# alarm waiting to happen. index.js earns its place: napi writes the version into
# a runtime guard and only rewrites it when somebody rebuilds, so a stale copy
# makes every install of the real package refuse its own native binary.
GENERATED = [
    ("bindings/node/index.js", "napi version guard", r"'@V@'"),
    ("bindings/node/package-lock.json", "lockfile", r'"version": "@V@"'),
    ("examples/node/package-lock.json", "example lockfile", r'"version": "@V@"'),
    ("web/package-lock.json", "web lockfile", r'"version": "@V@"'),
]


def read(rel: str) -> str | None:
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def workspace_version() -> str:
    text = read("Cargo.toml")
    if text is None:
        raise SystemExit("Cargo.toml not found; run this from the repository")
    match = re.search(r'(?m)^version = "([^"]+)"$', text)
    if match is None:
        raise SystemExit("Cargo.toml declares no workspace version")
    return match.group(1)


def citation_failures(version: str) -> list[str]:
    """`CITATION.cff` carries the version only once a release exists.

    Both keys are absent until a release is cut -- citing one that never
    happened is what the docs_examples guard forbids -- so this cannot demand
    them. What it can demand is that a version present here is *this* one: the
    file is outside every package manager's reach, so nothing else would notice
    it going stale.
    """
    text = read("CITATION.cff")
    if text is None:
        return ["CITATION.cff: missing"]
    declared = [
        line.split(":", 1)[1].strip().strip('"')
        for line in text.splitlines()
        if line.startswith("version:")
    ]
    if declared and declared[0] != version:
        return [f"CITATION.cff: cites {declared[0]}, the workspace is at {version}"]
    return []


def check(version: str, previous: str | None) -> int:
    failures: list[str] = []
    checked = 0

    for rel, what, pattern, expected in TOUCHPOINTS:
        text = read(rel)
        if text is None:
            failures.append(f"{rel}: missing, but listed as carrying the version")
            continue
        found = len(re.findall(pattern.replace("@V@", re.escape(version)), text))
        checked += 1
        if found != expected:
            failures.append(
                f"{rel}: {what} -- expected {expected} occurrence(s) of {version}, found {found}"
            )

    for rel, what, pattern in GENERATED:
        text = read(rel)
        if text is None:
            failures.append(f"{rel}: missing, but listed as carrying the version")
            continue
        checked += 1
        if not re.search(pattern.replace("@V@", re.escape(version)), text):
            failures.append(f"{rel}: {what} -- no occurrence of {version}; regenerate it")

    failures += citation_failures(version)

    # A stale copy of the previous version is the other half of the same mistake:
    # every file agreeing is not enough if one of them agrees on the old number.
    if previous is not None and previous != version:
        stale = []
        stale_sources = [(rel, pat) for rel, _, pat, _ in TOUCHPOINTS]
        stale_sources += [(rel, pat) for rel, _, pat in GENERATED]
        for rel, pattern in stale_sources:
            text = read(rel)
            if text is None:
                continue
            if re.search(pattern.replace("@V@", re.escape(previous)), text):
                stale.append(rel)
        # Cargo.lock names this project's own crates; third-party entries that
        # happen to share the version are none of our business.
        lock = read("Cargo.lock")
        if lock is not None:
            for block in lock.split("[[package]]"):
                if re.search(r'(?m)^name = "wickra-terminal', block) and re.search(
                    rf'(?m)^version = "{re.escape(previous)}"$', block
                ):
                    stale.append("Cargo.lock")
                    break
        for rel in sorted(set(stale)):
            failures.append(f"{rel}: still carries the previous version {previous}")

    print(f"version {version}: checked {checked} declarations")
    if failures:
        print("\nversion declarations disagree:", file=sys.stderr)
        for line in failures:
            print(f"  {line}", file=sys.stderr)
        return 1
    print("every declaration agrees.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--previous",
        help="also assert no declaration still carries this earlier version",
    )
    args = parser.parse_args()
    return check(workspace_version(), args.previous)


if __name__ == "__main__":
    raise SystemExit(main())
